// Seed data representing our mock backend database for the E2E Camps portal
export const initialCamps = [
  // --- 1. CONDUCTED CAMPS (Closed, Impact Logged) ---
  {
    id: "3-7729000039670",
    agency: "Publicis Group",
    holdingGroup: "Publicis",
    suite: "Video & Social",
    strategicGoal: "Product Activation",
    salesSegment: "LCS",
    curriculumLevel: "101",
    amEmail: "veraalejandro@google.com",
    product: "Apps Camp: W2AC",
    region: "EMEA",
    platform: "Meet",
    stage: "closed",
    status: "Impact Logged",
    nominationDate: "2026-01-22",
    discoveryStatus: "Submitted",
    discoveryData: { confidence: "Intermediate", topics: ["Apps Camp", "W2AC"] },
    deckType: "Customized Deck",
    scheduledTime: "2026-01-22T16:30:00Z",
    presenter: "mishravinay (Presenter)",
    liveQuestions: [],
    followUpSent: true,
    slaBreached: false,
    slaDaysRemaining: null,
    bfmUplift: 15.0,
    feedbackScore: 4.8,
    recordingArchived: true
  },
  {
    id: "5-5205000039465",
    agency: "JellyFish",
    holdingGroup: "Jellyfish",
    suite: "Video & Social",
    strategicGoal: "Product Activation",
    salesSegment: "LCS",
    curriculumLevel: "201",
    amEmail: "debankur@google.com",
    product: "YouTube Camp",
    region: "MENA",
    platform: "Meet",
    stage: "closed",
    status: "Impact Logged",
    nominationDate: "2026-01-21",
    discoveryStatus: "Submitted",
    discoveryData: { confidence: "Advanced", topics: ["YouTube Brand"] },
    deckType: "Customized Deck",
    scheduledTime: "2026-01-21T11:00:00Z",
    presenter: "ranjitsingh (Presenter)",
    liveQuestions: [],
    followUpSent: true,
    slaBreached: false,
    slaDaysRemaining: null,
    bfmUplift: 18.4,
    feedbackScore: 4.9,
    recordingArchived: true
  },
  {
    id: "4-5041000039971",
    agency: "Publicis Group",
    holdingGroup: "Publicis",
    suite: "Video & Social",
    strategicGoal: "Product Activation",
    salesSegment: "LCS",
    curriculumLevel: "201",
    amEmail: "shashanksr@google.com",
    product: "Apps Camp: iOS",
    region: "EMEA",
    platform: "Meet",
    stage: "closed",
    status: "Impact Logged",
    nominationDate: "2026-01-29",
    discoveryStatus: "Submitted",
    discoveryData: { confidence: "Intermediate", topics: ["iOS", "Apps"] },
    deckType: "Customized Deck",
    scheduledTime: "2026-01-29T14:00:00Z",
    presenter: "ruksanay (Presenter)",
    liveQuestions: [],
    followUpSent: true,
    slaBreached: false,
    slaDaysRemaining: null,
    bfmUplift: 22.0,
    feedbackScore: 4.7,
    recordingArchived: true
  },
  {
    id: "4-2781000039212",
    agency: "Carat",
    holdingGroup: "Dentsu",
    suite: "AI, Search & Commerce",
    strategicGoal: "Product Activation",
    salesSegment: "LCS",
    curriculumLevel: "101",
    amEmail: "fnasrulla@google.com",
    product: "One Search Camp",
    region: "EMEA",
    platform: "Meet",
    stage: "closed",
    status: "Impact Logged",
    nominationDate: "2026-01-19",
    discoveryStatus: "Submitted",
    discoveryData: { confidence: "Intermediate", topics: ["One Search"] },
    deckType: "Customized Deck",
    scheduledTime: "2026-01-19T10:00:00Z",
    presenter: "kumarikalyani (Presenter)",
    liveQuestions: [],
    followUpSent: true,
    slaBreached: false,
    slaDaysRemaining: null,
    bfmUplift: 16.0,
    feedbackScore: 4.5,
    recordingArchived: true
  },
  {
    id: "5-1877000039645",
    agency: "Havas",
    holdingGroup: "Havas",
    suite: "Google Marketing Platform (GMP)",
    strategicGoal: "Externalizing Solutions",
    salesSegment: "LCS",
    curriculumLevel: "201",
    amEmail: "gvenkat@google.com",
    product: "Measurement Camp",
    region: "AMER",
    platform: "Meet",
    stage: "closed",
    status: "Impact Logged",
    nominationDate: "2026-04-02",
    discoveryStatus: "Submitted",
    discoveryData: { confidence: "Advanced", topics: ["Measurement", "GTG"] },
    deckType: "Customized Deck",
    scheduledTime: "2026-04-02T15:00:00Z",
    presenter: "aditijain (Presenter)",
    liveQuestions: [],
    followUpSent: true,
    slaBreached: false,
    slaDaysRemaining: null,
    bfmUplift: 50.0,
    feedbackScore: 4.9,
    recordingArchived: true
  },
  {
    id: "0-8944000040599",
    agency: "Omnicom Group",
    holdingGroup: "Omnicom",
    suite: "AI, Search & Commerce",
    strategicGoal: "Product Activation",
    salesSegment: "LCS",
    curriculumLevel: "201",
    amEmail: "rampalp@google.com",
    product: "PMax Camp",
    region: "EMEA",
    platform: "Meet",
    stage: "closed",
    status: "Impact Logged",
    nominationDate: "2026-02-19",
    discoveryStatus: "Submitted",
    discoveryData: { confidence: "Advanced", topics: ["PMax", "AI"] },
    deckType: "Customized Deck",
    scheduledTime: "2026-02-19T11:00:00Z",
    presenter: "fnasrulla (Presenter)",
    liveQuestions: [],
    followUpSent: true,
    slaBreached: false,
    slaDaysRemaining: null,
    bfmUplift: 40.0,
    feedbackScore: 4.6,
    recordingArchived: true
  },
  {
    id: "8-1686000040892",
    agency: "WPP Group",
    holdingGroup: "WPP",
    suite: "Video & Social",
    strategicGoal: "Product Activation",
    salesSegment: "LCS",
    curriculumLevel: "201",
    amEmail: "fnasrulla@google.com",
    product: "YT Camp (VRC 2.0)",
    region: "EMEA",
    platform: "Meet",
    stage: "closed",
    status: "Impact Logged",
    nominationDate: "2026-04-28",
    discoveryStatus: "Submitted",
    discoveryData: { confidence: "Intermediate", topics: ["YT", "VRC 2.0"] },
    deckType: "Customized Deck",
    scheduledTime: "2026-04-28T10:30:00Z",
    presenter: "spinapala (Presenter)",
    liveQuestions: [],
    followUpSent: true,
    slaBreached: false,
    slaDaysRemaining: null,
    bfmUplift: 18.0,
    feedbackScore: 4.8,
    recordingArchived: true
  },
  {
    id: "9-1954000041233",
    agency: "KEYADE",
    holdingGroup: "Indy",
    suite: "AI, Search & Commerce",
    strategicGoal: "Product Activation",
    salesSegment: "LCS",
    curriculumLevel: "201",
    amEmail: "kumarikalyani@google.com",
    product: "One Search Camp",
    region: "MENA",
    platform: "Meet",
    stage: "closed",
    status: "Impact Logged",
    nominationDate: "2026-05-08",
    discoveryStatus: "Submitted",
    discoveryData: { confidence: "Advanced", topics: ["One Search", "AI MAX"] },
    deckType: "Customized Deck",
    scheduledTime: "2026-05-08T14:00:00Z",
    presenter: "shashanksr (Presenter)",
    liveQuestions: [],
    followUpSent: true,
    slaBreached: false,
    slaDaysRemaining: null,
    bfmUplift: 40.0,
    feedbackScore: 4.7,
    recordingArchived: true
  },

  // --- 2. PLANNED & SCHEDULED CAMPS (Pre-Camp / In-Camp, Scheduled) ---
  {
    id: "9-9073000039553",
    agency: "Smarter Ecommerce",
    holdingGroup: "Indy",
    suite: "Video & Social",
    strategicGoal: "Product Activation",
    salesSegment: "GCS",
    curriculumLevel: "101",
    amEmail: "ktaavitsainen@google.com",
    product: "Demand Gen Camp",
    region: "EMEA",
    platform: "Meet",
    stage: "pre-camp",
    status: "Awaiting Discovery",
    nominationDate: "2026-05-18",
    discoveryStatus: "Pending",
    discoveryData: null,
    deckType: "Standard Deck",
    scheduledTime: "2026-06-15T10:00:00Z",
    presenter: "Taylor Chen (Presenter)",
    liveQuestions: [],
    followUpSent: false,
    slaBreached: false,
    slaDaysRemaining: 3,
    bfmUplift: null,
    feedbackScore: null,
    recordingArchived: false
  },
  {
    id: "2-1936000041090",
    agency: "Dentsu Group",
    holdingGroup: "Dentsu",
    suite: "Video & Social",
    strategicGoal: "Product Activation",
    salesSegment: "LCS",
    curriculumLevel: "201",
    amEmail: "latti@google.com",
    product: "Demand Gen Camp",
    region: "EMEA",
    platform: "Meet",
    stage: "pre-camp",
    status: "Awaiting Discovery",
    nominationDate: "2026-05-22",
    discoveryStatus: "Pending",
    discoveryData: null,
    deckType: "Standard Deck",
    scheduledTime: "2026-06-03T14:00:00Z",
    presenter: "Alex Rivera (Presenter)",
    liveQuestions: [],
    followUpSent: false,
    slaBreached: false,
    slaDaysRemaining: 3,
    bfmUplift: null,
    feedbackScore: null,
    recordingArchived: false
  },
  {
    id: "9-9027000041336",
    agency: "TRKKN",
    holdingGroup: "Indy",
    suite: "Google Marketing Platform (GMP)",
    strategicGoal: "Externalizing Solutions",
    salesSegment: "LCS",
    curriculumLevel: "201",
    amEmail: "dimitrim@google.com",
    product: "Measurement Camp",
    region: "AMER",
    platform: "Meet",
    stage: "pre-camp",
    status: "Awaiting Discovery",
    nominationDate: "2026-05-20",
    discoveryStatus: "Pending",
    discoveryData: null,
    deckType: "Standard Deck",
    scheduledTime: "2026-06-03T11:30:00Z",
    presenter: "Taylor Chen (Presenter)",
    liveQuestions: [],
    followUpSent: false,
    slaBreached: false,
    slaDaysRemaining: 3,
    bfmUplift: null,
    feedbackScore: null,
    recordingArchived: false
  },

  // --- 3. PROPOSED CAMPS (Nomination, Pending Kickoff) ---
  {
    id: "4-6961000040338",
    agency: "Havas",
    holdingGroup: "Havas",
    suite: "Google Marketing Platform (GMP)",
    strategicGoal: "Obviating Troubleshooting",
    salesSegment: "LCS",
    curriculumLevel: "201",
    amEmail: "majdag@google.com",
    product: "DV360 Camp",
    region: "EMEA",
    platform: "Meet",
    stage: "nomination",
    status: "Pending Kickoff",
    nominationDate: "2026-05-25",
    discoveryStatus: "Not Sent",
    discoveryData: null,
    deckType: "Standard Deck",
    scheduledTime: null,
    presenter: null,
    liveQuestions: [],
    followUpSent: false,
    slaBreached: false,
    slaDaysRemaining: null,
    bfmUplift: null,
    feedbackScore: null,
    recordingArchived: false
  },
  {
    id: "5-5379000040440",
    agency: "Omnicom Group",
    holdingGroup: "Omnicom",
    suite: "Video & Social",
    strategicGoal: "Product Activation",
    salesSegment: "LCS",
    curriculumLevel: "201",
    amEmail: "cmschultz@google.com",
    product: "YouTube Camp (CPH)",
    region: "AMER",
    platform: "Meet",
    stage: "nomination",
    status: "Pending Kickoff",
    nominationDate: "2026-05-26",
    discoveryStatus: "Not Sent",
    discoveryData: null,
    deckType: "Standard Deck",
    scheduledTime: null,
    presenter: null,
    liveQuestions: [],
    followUpSent: false,
    slaBreached: false,
    slaDaysRemaining: null,
    bfmUplift: null,
    feedbackScore: null,
    recordingArchived: false
  },
  {
    id: "7-0898000041117",
    agency: "Kulfi",
    holdingGroup: "Indy",
    suite: "Video & Social",
    strategicGoal: "Product Activation",
    salesSegment: "GCS",
    curriculumLevel: "101",
    amEmail: "varshamohan@google.com",
    product: "YT Camp (CPH Training)",
    region: "APAC",
    platform: "Meet",
    stage: "nomination",
    status: "Pending Kickoff",
    nominationDate: "2026-05-26",
    discoveryStatus: "Not Sent",
    discoveryData: null,
    deckType: "Standard Deck",
    scheduledTime: null,
    presenter: null,
    liveQuestions: [],
    followUpSent: false,
    slaBreached: false,
    slaDaysRemaining: null,
    bfmUplift: null,
    feedbackScore: null,
    recordingArchived: false
  },

  // --- 4. CANCELLED / CLOSED CAMPS (Closed, Cancelled/Closed) ---
  {
    id: "3-7728000039774",
    agency: "Disability Guide",
    holdingGroup: "Indy",
    suite: "Video & Social",
    strategicGoal: "Product Activation",
    salesSegment: "GCS",
    curriculumLevel: "101",
    amEmail: "am.disability@google.com",
    product: "Demand Gen Camp",
    region: "AMER",
    platform: "Meet",
    stage: "closed",
    status: "Cancelled by AM",
    nominationDate: "2026-05-10",
    discoveryStatus: "Not Sent",
    discoveryData: null,
    deckType: "Standard Deck",
    scheduledTime: null,
    presenter: null,
    liveQuestions: [],
    followUpSent: false,
    slaBreached: false,
    slaDaysRemaining: null,
    bfmUplift: null,
    feedbackScore: null,
    recordingArchived: false
  },
  {
    id: "0-7702000040974",
    agency: "Direct Agents",
    holdingGroup: "Indy",
    suite: "AI, Search & Commerce",
    strategicGoal: "Product Activation",
    salesSegment: "GCS",
    curriculumLevel: "101",
    amEmail: "am.directagents@google.com",
    product: "One Search Camp",
    region: "AMER",
    platform: "Meet",
    stage: "closed",
    status: "Closed as no Response",
    nominationDate: "2026-04-18",
    discoveryStatus: "Not Sent",
    discoveryData: null,
    deckType: "Standard Deck",
    scheduledTime: null,
    presenter: null,
    liveQuestions: [],
    followUpSent: false,
    slaBreached: true,
    slaDaysRemaining: 0,
    bfmUplift: null,
    feedbackScore: null,
    recordingArchived: false
  }
];

export const initialLogs = [
  { timestamp: "2026-05-18T11:00:00Z", level: "INFO", message: "System initialized. Camps databases synchronized with Cases Connect." },
  { timestamp: "2026-05-18T11:05:00Z", level: "INFO", message: "Nomination ticket parsed for Omnicom Group - Case 2-9828." },
  { timestamp: "2026-05-18T11:15:00Z", level: "SUCCESS", message: "Pre-Camp Discovery Link sent to GroupM - AM Ashlee." }
];

export const initialTasks = [
  { id: "t1", title: "Assign Lead Presenter to Case 2-9828 (Omnicom)", assignee: "Presenter", done: false, dueDate: "2026-05-20" },
  { id: "t2", title: "Review GroupM Discovery Service menu selection", assignee: "Presenter", done: false, dueDate: "2026-05-21" },
  { id: "t3", title: "Answer S2S API escalated question for Case 4-9901 (Publicis)", assignee: "PM", done: false, dueDate: "2026-05-19" }
];

export const initialChats = [
  { timestamp: "2026-05-18T11:30:00Z", sender: "Presenter", text: "Just kicked off the pre-camp scheduler for GroupM. AM team, please push for discovery form submission!" },
  { timestamp: "2026-05-18T11:45:00Z", sender: "AM", text: "Copy that! Pushing GroupM practitioners to fill it by tomorrow." },
  { timestamp: "2026-05-18T12:00:00Z", sender: "PM", text: "Monitoring the CM360 escalated questions in the PM queue. Will log authoritative replies shortly." }
];

export const initialTemplates = {
  discovery: {
    subject: "ACTION REQUIRED: Pre-Camp Discovery Form for {{AGENCY}}",
    body: "Hi {{AM_NAME}},\n\nYour {{PRODUCT}} Camp has been kicked off by presenter {{PRESENTER}}!\n\nPlease share this secure link with your agency contacts at {{AGENCY}} so they can complete their Discovery Form:\n\nhttps://camps.google.com/portal/agency-discovery?caseId={{CASE_ID}}\n\nThis form must be submitted by {{SLA_DATE}} to avoid applying the default deck protocol.\n\nBest,\nGPEG Camps Team"
  },
  resolution: {
    subject: "RESOLVED Q&A: Case {{CASE_ID}} - {{AGENCY}}",
    body: "Hi {{AM_NAME}},\n\nOur Product Lead / PM has resolved the escalated technical question for {{AGENCY}}.\n\nQuestion: \"{{QUESTION}}\"\nAnswer: \"{{ANSWER}}\"\n\nThis has been automatically embedded into your follow-up draft. You can now send the final post-camp package!\n\nBest,\nGPEG Camps Team"
  },
  followup: {
    subject: "FOLLOW-UP PACKAGE: GPEG {{PRODUCT}} Camp - {{AGENCY}}",
    body: "Hi {{AM_NAME}},\n\nThank you for coordinating the GPEG {{PRODUCT}} Camp for {{AGENCY}}!\n\nAs promised, please find the follow-up resources package below:\n1. Training Presentation (Customized PDF)\n2. Workshop Session Recording (MP4)\n3. Agency feedback Survey Link: https://camps.google.com/portal/agency-discovery?caseId={{CASE_ID}}\n\n--- LIVE CAPTURED Q&A SESSION RESOLUTION ---\n{{QA_CONTENT}}\n\nBest,\nGPEG Camps Team"
  }
};

// --- 10-TAB CONSOLE DATABASES SEEDS ---
export const initialTeamRoster = [
  { id: "r1", name: "Taylor Chen", role: "Presenter", status: "Clocked In", location: "Remote 🏠", timestamp: "2026-05-19T08:30:00Z" },
  { id: "r2", name: "Alex Rivera", role: "Presenter", status: "Clocked In", location: "Office 🏢", timestamp: "2026-05-19T09:00:00Z" },
  { id: "r3", name: "Jordan Blake", role: "Presenter", status: "Yet to Login", location: "Remote 🏠", timestamp: "N/A" },
  { id: "r4", name: "Angela Chang", role: "SME Partner", status: "Clocked In", location: "Office 🏢", timestamp: "2026-05-19T08:15:00Z" },
  { id: "r5", name: "Sarah Jenkins", role: "Account AM", status: "Clocked Out", location: "Remote 🏠", timestamp: "2026-05-18T18:00:00Z" }
];

export const initialWeeklyUtilization = [
  { id: "u1", weekEnding: "2026-05-22", name: "Taylor Chen", expectedHrs: 40, loggedHrs: 36, status: "Optimal" },
  { id: "u2", weekEnding: "2026-05-22", name: "Alex Rivera", expectedHrs: 40, loggedHrs: 45, status: "Overutilized" },
  { id: "u3", weekEnding: "2026-05-22", name: "Jordan Blake", expectedHrs: 40, loggedHrs: 22, status: "Underutilized" },
  { id: "u4", weekEnding: "2026-05-15", name: "Taylor Chen", expectedHrs: 40, loggedHrs: 40, status: "Optimal" },
  { id: "u5", weekEnding: "2026-05-15", name: "Alex Rivera", expectedHrs: 40, loggedHrs: 38, status: "Optimal" }
];

export const initialEffortLogs = [
  { id: "e1", caseId: "1-4893000041135", agency: "GroupM", name: "Taylor Chen", taskType: "Pre-Camp", taskName: "Discovery Form Customization Review", hours: 4.5 },
  { id: "e2", caseId: "3-7721000010200", agency: "Dentsu Aegis", name: "Alex Rivera", taskType: "In-Camp", taskName: "Live Session Workshop Delivery", hours: 2.0 },
  { id: "e3", caseId: "4-9901000031200", agency: "Publicis Groupe", name: "Jordan Blake", taskType: "Post-Camp", taskName: "Q&A Technical Resolution & Packing", hours: 3.0 },
  { id: "e4", caseId: "2-9828000040100", agency: "Omnicom Group", name: "Taylor Chen", taskType: "Pre-Camp", taskName: "Presenter Scheduling Coordination", hours: 1.5 }
];

export const mosCamps = [
  { campId: "c_yt", strategicGoal: "Activate", category: "YouTube +", campName: "YouTube Brand Camp", launchStatus: "Available" },
  { campId: "c_dg", strategicGoal: "Activate", category: "YouTube +", campName: "Demand Gen Camp", launchStatus: "Available" },
  { campId: "c_pmax", strategicGoal: "Activate", category: "Search +", campName: "PMax & Brand Camp", launchStatus: "Available" },
  { campId: "c_gmp", strategicGoal: "Obviate", category: "Platform - GMP +", campName: "GMP Campaign Foundations", launchStatus: "Available" }
];

export const mosTopics = [
  { topicId: "t_yt_1", campId: "c_yt", topicCategory: "YouTube Brand", activationPath: "101", topicName: "101- Introduction to AI Powered Video - VRC & VVC Overview", durationMinutes: 60, targetBfm: "Brand AI-Powered Depth", baseDeckTitle: "gPEG ( Base Deck ) - YT Camp (Intro, VRC & VVC Overview)" },
  { topicId: "t_yt_2", campId: "c_yt", topicCategory: "YouTube Brand", activationPath: "201", topicName: "201- Deep Dive: Advanced Bidding & Creative Formats", durationMinutes: 90, targetBfm: "Brand AI-Powered Depth", baseDeckTitle: "gPEG ( Base Deck ) - YT Camp (Bidding & Advanced Formats)" },
  { topicId: "t_dg_1", campId: "c_dg", topicCategory: "Display & Video", activationPath: "101", topicName: "101- Introduction to Demand Gen Social & Bidding", durationMinutes: 60, targetBfm: "Demand Gen Social Growth", baseDeckTitle: "gPEG ( Base Deck ) - DemandGen Camp (Social & Bidding)" },
  { topicId: "t_pmax_1", campId: "c_pmax", topicCategory: "Search & Commerce", activationPath: "201", topicName: "201- Search & PMax Bidding Custom Allocations", durationMinutes: 90, targetBfm: "PMax AI Bidding Efficiency", baseDeckTitle: "gPEG ( Base Deck ) - PMax Camp (Bidding & Budget)" },
  { topicId: "t_gmp_1", campId: "c_gmp", topicCategory: "GMP Platforms", activationPath: "101", topicName: "101- GMP CM360 Foundations & S2S API variables", durationMinutes: 60, targetBfm: "GMP Campaign Obviation", baseDeckTitle: "gPEG ( Base Deck ) - CM360 Camp (Foundations & Ingress)" }
];
